"""initial schema

Revision ID: 7e09bd091feb
Revises: 
Create Date: 2026-09-12 15:56:35.173851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e09bd091feb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True, comment='대표 이메일. 소셜사가 미제공하면 NULL'),
    sa.Column('marketing_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='계정 단위 마케팅 동의. 법적 기준은 이 값이며 user_profile 쪽은 조회 시점 기록일 뿐이다'),
    sa.Column('consent_updated_at', sa.DateTime(timezone=True), nullable=True, comment='마케팅 동의를 마지막으로 변경한 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_app_user')),
    comment='서비스 계정. 소셜 로그인으로만 생성된다'
    )
    op.create_index('ix_app_user_email', 'app_user', ['email'], unique=False, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('batch_run',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('batch_type', sa.String(length=20), nullable=False, comment='MATURITY = 만기일 지난 user_holding 을 만기 처리하는 일배치. 사용자 접속과 무관하게 돌아야 한다'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'RUNNING'"), nullable=False, comment='RUNNING 은 시작 시점에 행을 먼저 넣기 위해 추가한 값'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("batch_type IN ('COLLECT', 'CRAWL', 'VERIFY', 'PARSE', 'MATURITY')", name=op.f('ck_batch_run_batch_type')),
    sa.CheckConstraint("status = 'RUNNING' OR finished_at IS NOT NULL", name=op.f('ck_batch_run_terminal')),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL')", name=op.f('ck_batch_run_status')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_batch_run_finished_at')),
    sa.CheckConstraint('processed_count >= 0 AND failed_count >= 0', name=op.f('ck_batch_run_counts')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_batch_run')),
    comment='배치 실행 1회. 수집된 모든 행이 이 run_id 를 들고 다녀 추적 단위가 된다'
    )
    op.create_index('ix_batch_run_batch_type', 'batch_run', ['batch_type', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('institution',
    sa.Column('institution_code', sa.String(length=20), nullable=False, comment='금감원 금융회사코드(fin_co_no). 공시에 없는 기관은 자체 코드 부여'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='정식 명칭 1개. 표기 변형은 institution_alias 로 흡수한다'),
    sa.Column('institution_type', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True, comment='지역은행·신협의 영업 지역. 전국구면 NULL'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("institution_type IN ('은행', '저축은행', '신협')", name=op.f('ck_institution_institution_type')),
    sa.PrimaryKeyConstraint('institution_code', name=op.f('pk_institution')),
    sa.UniqueConstraint('name', name=op.f('uq_institution_name')),
    comment='금융기관 마스터. 기관을 가리키는 모든 곳은 이름이 아니라 이 코드를 쓴다'
    )
    op.create_table('crawl_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('page_hash', sa.String(length=64), nullable=False, comment='본문 SHA-256. 이전 run 과 같은 해시면 파싱을 건너뛴다'),
    sa.Column('has_offer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['batch_run.run_id'], name=op.f('fk_crawl_history_run_id_batch_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_history')),
    comment='크롤링한 게시글 1건. 같은 글을 다음 배치에서 또 봐도 행은 새로 쌓인다'
    )
    op.create_index('ix_crawl_history_page_hash', 'crawl_history', ['page_hash'], unique=False)
    op.create_index('ix_crawl_history_run_id', 'crawl_history', ['run_id'], unique=False)
    op.create_table('institution_alias',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('institution_code', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['institution_code'], ['institution.institution_code'], name=op.f('fk_institution_alias_institution_code_institution'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_alias')),
    sa.UniqueConstraint('alias', name=op.f('uq_institution_alias_alias')),
    comment='크롤링 문자열을 코드로 되돌리는 사전. "KB국민", "국민은행", "국민" 을 모두 같은 코드로 보낸다'
    )
    op.create_table('social_account',
    sa.Column('social_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='소셜사가 발급한 고유 ID (sub/id)'),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('GOOGLE', 'KAKAO', 'NAVER')", name=op.f('ck_social_account_provider')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], name=op.f('fk_social_account_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('social_id', name=op.f('pk_social_account')),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_social_account_provider')),
    sa.UniqueConstraint('user_id', 'provider', name=op.f('uq_social_account_user_id')),
    comment='소셜 로그인 연결. 한 계정에 여러 provider 연결 가능'
    )
    op.create_table('user_profile',
    sa.Column('profile_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('capital', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_saving', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('period_months', sa.Integer(), nullable=False),
    sa.Column('withdraw_flexibility', sa.String(length=20), nullable=True, comment='중도인출 가능성. 값 집합은 기획 확정 후 CHECK 추가'),
    sa.Column('main_bank_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='만 나이 계산에 필요해 원본 보관. 청년·노인 우대조건 판정에 쓴다'),
    sa.Column('salary_transfer', sa.Boolean(), nullable=True, comment='NULL = 아직 물어보지 않음 / 확인 불가'),
    sa.Column('auto_transfer', sa.Boolean(), nullable=True),
    sa.Column('monthly_card_usage', sa.BigInteger(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='이 조회 건에서 받은 동의 기록. 계정 단위 최신 동의는 app_user.marketing_consent 를 본다'),
    sa.Column('app_install', sa.Boolean(), nullable=True),
    sa.Column('accepts_membership', sa.Boolean(), nullable=True, comment='신협·새마을금고 조합원 가입(출자금 납입) 의향. 예탁금 가입 자격 판정에 쓴다. NULL = 미확인'),
    sa.Column('tax_exempt_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='올해 이미 사용한 비과세 한도(원)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capital > 0 OR monthly_saving > 0', name=op.f('ck_user_profile_has_money')),
    sa.CheckConstraint('capital >= 0 AND monthly_saving >= 0 AND tax_exempt_used >= 0 AND (monthly_card_usage IS NULL OR monthly_card_usage >= 0)', name=op.f('ck_user_profile_amounts')),
    sa.CheckConstraint('period_months > 0', name=op.f('ck_user_profile_period_months')),
    sa.ForeignKeyConstraint(['main_bank_code'], ['institution.institution_code'], name=op.f('fk_user_profile_main_bank_code_institution'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], name=op.f('fk_user_profile_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_user_profile')),
    comment='조회 1건의 입력값 스냅샷. 사용자가 다시 조회하면 새 행이 쌓인다'
    )
    op.create_index('ix_user_profile_user_id', 'user_profile', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('special_offer',
    sa.Column('offer_id', sa.String(length=64), nullable=False, comment='출처 URL + 상품명 해시 등으로 만든 애플리케이션 발급 ID'),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('crawl_history_id', sa.BigInteger(), nullable=True, comment='이 특판을 발견한 크롤링 건. 원문 추적용'),
    sa.Column('claimed_institution', sa.String(length=100), nullable=False, comment='커뮤니티 글에 적힌 기관명 원문. 검증 단계에서 institution_alias 로 코드를 찾아 붙인다'),
    sa.Column('institution_type', sa.String(length=20), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('claimed_product_name', sa.String(length=200), nullable=True),
    sa.Column('claimed_base_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('claimed_max_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='커뮤니티 글이 주장한 금리. 검증 전 값이라 노출 금지'),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('institution_code', sa.String(length=20), nullable=True, comment='기관 매칭에 성공한 뒤 채워진다. NULL 이면 아직 미해결'),
    sa.Column('matched_product_name', sa.String(length=200), nullable=True),
    sa.Column('verified_amount_cap', sa.BigInteger(), nullable=True),
    sa.Column('verified_terms_text', sa.Text(), nullable=True),
    sa.Column('verify_source_url', sa.String(length=1000), nullable=True),
    sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rejected_reason', sa.String(length=200), nullable=True),
    sa.Column('verify_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_verify_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("institution_type IS NULL OR institution_type IN ('은행', '저축은행', '신협')", name=op.f('ck_special_offer_institution_type')),
    sa.CheckConstraint("product_type IS NULL OR product_type IN ('예금', '적금', '예탁금')", name=op.f('ck_special_offer_product_type')),
    sa.CheckConstraint("source_type IS NULL OR source_type IN ('지역은행공식', '커뮤니티')", name=op.f('ck_special_offer_source_type')),
    sa.CheckConstraint("verification_status <> 'REJECTED' OR rejected_reason IS NOT NULL", name=op.f('ck_special_offer_rejected_reason')),
    sa.CheckConstraint("verification_status <> 'VERIFIED' OR (verified_at IS NOT NULL AND verify_source_url IS NOT NULL AND institution_code IS NOT NULL)", name=op.f('ck_special_offer_verified_evidence')),
    sa.CheckConstraint("verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')", name=op.f('ck_special_offer_verification_status')),
    sa.CheckConstraint('(claimed_base_rate IS NULL OR claimed_base_rate >= 0) AND (claimed_max_rate IS NULL OR claimed_base_rate IS NULL OR claimed_max_rate >= claimed_base_rate)', name=op.f('ck_special_offer_rates')),
    sa.CheckConstraint('verify_attempt_count >= 0', name=op.f('ck_special_offer_verify_attempt_count')),
    sa.ForeignKeyConstraint(['crawl_history_id'], ['crawl_history.id'], name=op.f('fk_special_offer_crawl_history_id_crawl_history'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_code'], ['institution.institution_code'], name=op.f('fk_special_offer_institution_code_institution')),
    sa.ForeignKeyConstraint(['run_id'], ['batch_run.run_id'], name=op.f('fk_special_offer_run_id_batch_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', name=op.f('pk_special_offer')),
    comment='커뮤니티/지역은행에서 발견한 특판 후보. 검증 전에는 사용자에게 노출하지 않는다'
    )
    op.create_index('ix_special_offer_run_id', 'special_offer', ['run_id'], unique=False)
    op.create_index('ix_special_offer_verification_status', 'special_offer', ['verification_status', sa.literal_column('discovered_at DESC')], unique=False)
    op.create_table('user_portfolio',
    sa.Column('portfolio_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_type', sa.String(length=10), nullable=False),
    sa.Column('goal_amount', sa.BigInteger(), nullable=True),
    sa.Column('goal_date', sa.Date(), nullable=True),
    sa.Column('after_tax_total', sa.BigInteger(), nullable=True, comment='만기 시 예상 세후 수령액(원)'),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'진행중'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("portfolio_type IN ('단순형', '균형형', '최대형')", name=op.f('ck_user_portfolio_portfolio_type')),
    sa.CheckConstraint("status IN ('진행중', '완료')", name=op.f('ck_user_portfolio_status')),
    sa.CheckConstraint('(goal_amount IS NULL OR goal_amount > 0) AND (after_tax_total IS NULL OR after_tax_total >= 0)', name=op.f('ck_user_portfolio_amounts')),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], name=op.f('fk_user_portfolio_profile_id_user_profile'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], name=op.f('fk_user_portfolio_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', name=op.f('pk_user_portfolio')),
    comment='사용자가 실제로 선택한 배분안. 제안만 하고 안 고른 안은 저장하지 않는다'
    )
    op.create_index('ix_user_portfolio_profile_id', 'user_portfolio', ['profile_id'], unique=False)
    op.create_index('ix_user_portfolio_user_id', 'user_portfolio', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_profile_bank',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['institution_code'], ['institution.institution_code'], name=op.f('fk_user_profile_bank_institution_code_institution')),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], name=op.f('fk_user_profile_bank_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_bank')),
    sa.UniqueConstraint('profile_id', 'institution_code', name=op.f('uq_user_profile_bank_profile_id')),
    comment='보유(거래 가능) 은행 복수선택'
    )
    op.create_table('user_profile_extra',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False, comment='product_condition.condition_type 과 반드시 같은 어휘를 쓴다. 어긋나면 우대금리가 조용히 누락된다'),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_value', sa.String(length=255), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('answer_value IS NULL OR answered_at IS NOT NULL', name=op.f('ck_user_profile_extra_answered')),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], name=op.f('fk_user_profile_extra_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_extra')),
    comment='고정 문항으로 못 채운 우대조건을 챗봇이 되물은 기록'
    )
    op.create_index('ix_user_profile_extra_profile_id', 'user_profile_extra', ['profile_id'], unique=False)
    op.create_table('user_profile_social',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.CheckConstraint("category IN ('다자녀', '한부모', '다문화', '신혼부부', '탈북자')", name=op.f('ck_user_profile_social_category')),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], name=op.f('fk_user_profile_social_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_social')),
    sa.UniqueConstraint('profile_id', 'category', name=op.f('uq_user_profile_social_profile_id')),
    comment='사회적 배려 대상 복수선택. 우대금리 가산 판단에 쓴다'
    )
    op.create_table('user_profile_tax_exempt',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], name=op.f('fk_user_profile_tax_exempt_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_tax_exempt')),
    sa.UniqueConstraint('profile_id', 'category', name=op.f('uq_user_profile_tax_exempt_profile_id')),
    comment='비과세 대상 항목 복수선택 (청년/노인/장애인 등)'
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(length=64), nullable=False, comment="공시 = 금융회사코드 + 상품코드 조합, 특판 = 'SP-' || offer_id. 배치 간 안정적이어야 한다"),
    sa.Column('offer_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('institution_code', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('amount_min', sa.BigInteger(), nullable=True, comment='최소 가입금액(예금) / 최소 총 납입액(적금)'),
    sa.Column('amount_cap', sa.BigInteger(), nullable=True, comment='최대 가입금액(예금) / 최대 총 납입액(적금)'),
    sa.Column('monthly_min', sa.BigInteger(), nullable=True, comment='적금 월 최소 납입액. 예금은 NULL'),
    sa.Column('monthly_cap', sa.BigInteger(), nullable=True, comment='적금 월 최대 납입액. 총 한도와 별개다 - 이걸 모르면 월 배분액이 한도를 넘는 배분안이 나온다'),
    sa.Column('terms_text', sa.Text(), nullable=True, comment='우대조건 파싱(LLM)의 입력 원문'),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('join_channel', sa.String(length=20), nullable=True),
    sa.Column('membership_required', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='조합원 가입(출자금)이 있어야 가입 가능. 신협·새마을금고 예탁금. 우대조건이 아니라 자격이다'),
    sa.Column('new_customer_only', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='해당 기관 신규 고객 전용'),
    sa.Column('min_age', sa.Integer(), nullable=True, comment='가입 가능 최소 만 나이. 청년 전용 상품 등'),
    sa.Column('max_age', sa.Integer(), nullable=True, comment='가입 가능 최대 만 나이'),
    sa.Column('parse_status', sa.String(length=10), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('snapshot_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='이 상품 정보가 유효한 기준일. 지난 날짜면 재조회 대상'),
    sa.Column('sale_end_date', sa.Date(), nullable=True, comment='판매 종료 예정일. 특판은 채워지고 공시 상품은 대개 NULL - 그쪽은 snapshot_date 가 오래되면 사라진 것으로 본다'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='추천 후보에서 뺄 때 쓴다. 행을 지우면 가입자의 금리 근거가 끊기므로 삭제 대신 이 값을 내린다'),
    sa.CheckConstraint("(source = 'SPECIAL' AND offer_id IS NOT NULL) OR (source = 'OFFICIAL' AND offer_id IS NULL)", name=op.f('ck_product_source_offer')),
    sa.CheckConstraint("join_channel IS NULL OR join_channel IN ('비대면', '영업점', '전체')", name=op.f('ck_product_join_channel')),
    sa.CheckConstraint("parse_status IN ('PENDING', 'PARSED', 'FAILED')", name=op.f('ck_product_parse_status')),
    sa.CheckConstraint("product_type = '적금' OR (monthly_min IS NULL AND monthly_cap IS NULL)", name=op.f('ck_product_monthly_only_savings')),
    sa.CheckConstraint("product_type IN ('예금', '적금', '예탁금')", name=op.f('ck_product_product_type')),
    sa.CheckConstraint("source IN ('OFFICIAL', 'SPECIAL')", name=op.f('ck_product_source')),
    sa.CheckConstraint('(amount_min IS NULL OR amount_min > 0) AND (amount_cap IS NULL OR amount_cap > 0) AND (monthly_min IS NULL OR monthly_min > 0) AND (monthly_cap IS NULL OR monthly_cap > 0) AND (amount_min IS NULL OR amount_cap IS NULL OR amount_min <= amount_cap) AND (monthly_min IS NULL OR monthly_cap IS NULL OR monthly_min <= monthly_cap)', name=op.f('ck_product_amounts')),
    sa.CheckConstraint('(min_age IS NULL OR min_age >= 0) AND (max_age IS NULL OR max_age >= 0) AND (min_age IS NULL OR max_age IS NULL OR min_age <= max_age)', name=op.f('ck_product_age')),
    sa.ForeignKeyConstraint(['institution_code'], ['institution.institution_code'], name=op.f('fk_product_institution_code_institution')),
    sa.ForeignKeyConstraint(['offer_id'], ['special_offer.offer_id'], name=op.f('fk_product_offer_id_special_offer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['batch_run.run_id'], name=op.f('fk_product_run_id_batch_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product')),
    sa.UniqueConstraint('offer_id', name=op.f('uq_product_offer_id')),
    comment='상품 기본정보(금감원 baseList 에 대응). 금리는 기간마다 달라서 product_option 이 들고 있다'
    )
    op.create_index('ix_product_institution_code', 'product', ['institution_code'], unique=False)
    op.create_index('ix_product_product_type', 'product', ['product_type'], unique=False, postgresql_where=sa.text("parse_status = 'PARSED' AND is_active"))
    op.create_index('ix_product_run_id', 'product', ['run_id'], unique=False)
    op.create_index('ix_product_snapshot_date', 'product', ['snapshot_date'], unique=False)
    op.create_table('special_offer_option',
    sa.Column('offer_option_id', sa.String(length=96), nullable=False, comment='offer_id + 기간 + 이자방식 조합. 승격 시 product_option 으로 1:1 옮겨간다'),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('period_months', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=10), server_default=sa.text("'단리'"), nullable=False),
    sa.Column('reserve_type', sa.String(length=20), server_default=sa.text("'해당없음'"), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint("rate_type IN ('단리', '복리')", name=op.f('ck_special_offer_option_rate_type')),
    sa.CheckConstraint("reserve_type IN ('해당없음', '정액적립식', '자유적립식')", name=op.f('ck_special_offer_option_reserve_type')),
    sa.CheckConstraint('base_rate >= 0 AND max_rate >= base_rate', name=op.f('ck_special_offer_option_rates')),
    sa.CheckConstraint('period_months > 0', name=op.f('ck_special_offer_option_period_months')),
    sa.ForeignKeyConstraint(['offer_id'], ['special_offer.offer_id'], name=op.f('fk_special_offer_option_offer_id_special_offer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_option_id', name=op.f('pk_special_offer_option')),
    sa.UniqueConstraint('offer_id', 'period_months', 'rate_type', 'reserve_type', name=op.f('uq_special_offer_option_offer_id')),
    comment='은행 사이트에서 확인한 특판의 기간별 금리. 특판도 12/24개월 식으로 여러 기간을 줄 수 있다'
    )
    op.create_index('ix_special_offer_option_offer_id', 'special_offer_option', ['offer_id'], unique=False)
    op.create_table('product_condition',
    sa.Column('condition_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False, comment='닫힌 어휘 목록 확정 필요. user_profile_extra.condition_type 과 같은 값을 써야 매칭이 된다'),
    sa.Column('rate_bonus', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('threshold_value', sa.BigInteger(), nullable=True),
    sa.Column('threshold_unit', sa.String(length=10), nullable=True),
    sa.Column('applies_period_min', sa.Integer(), nullable=True),
    sa.Column('applies_period_max', sa.Integer(), nullable=True),
    sa.Column('exclusive_group', sa.String(length=50), nullable=True, comment='같은 그룹의 조건은 하나만 적용된다 (택1 우대)'),
    sa.Column('evidence_text', sa.Text(), nullable=True, comment='가산 근거가 된 약관 원문 인용. 사용자에게 그대로 보여준다'),
    sa.Column('evidence_url', sa.String(length=1000), nullable=True),
    sa.Column('verification_status', sa.String(length=10), nullable=True, comment='파싱 결과와 약관 대조 결과. EXCESS = 약관에 없는 조건을 만들어냄'),
    sa.Column('confidence_badge', sa.String(length=10), server_default=sa.text("'검수대기'"), nullable=False),
    sa.CheckConstraint("confidence_badge IN ('확인됨', '검수대기')", name=op.f('ck_product_condition_confidence_badge')),
    sa.CheckConstraint("threshold_unit IS NULL OR threshold_unit IN ('KRW', 'COUNT', 'MONTH')", name=op.f('ck_product_condition_threshold_unit')),
    sa.CheckConstraint("verification_status IS NULL OR verification_status IN ('EXACT', 'MISSING', 'EXCESS')", name=op.f('ck_product_condition_verification_status')),
    sa.CheckConstraint('(threshold_value IS NULL) = (threshold_unit IS NULL)', name=op.f('ck_product_condition_threshold_pair')),
    sa.CheckConstraint('applies_period_min IS NULL OR applies_period_max IS NULL OR applies_period_min <= applies_period_max', name=op.f('ck_product_condition_applies_period')),
    sa.CheckConstraint('rate_bonus >= 0', name=op.f('ck_product_condition_rate_bonus')),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_product_condition_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condition_id', name=op.f('pk_product_condition')),
    comment='약관에서 뽑아낸 우대조건 1개. 기간 제한은 applies_period_* 로 표현하므로 상품 단위로 붙인다'
    )
    op.create_index('ix_product_condition_product_id', 'product_condition', ['product_id'], unique=False)
    op.create_table('product_option',
    sa.Column('option_id', sa.String(length=96), nullable=False, comment='product_id + 기간 + 이자방식 조합으로 결정적으로 생성. 배치가 upsert 해도 user_holding 링크가 유지된다'),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('period_months', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=10), server_default=sa.text("'단리'"), nullable=False),
    sa.Column('reserve_type', sa.String(length=20), server_default=sa.text("'해당없음'"), nullable=False, comment="적금의 적립 방식. 예금은 '해당없음'. NULL 을 쓰면 UNIQUE 가 중복을 못 막아서 기본값을 둔다"),
    sa.Column('base_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint("rate_type IN ('단리', '복리')", name=op.f('ck_product_option_rate_type')),
    sa.CheckConstraint("reserve_type IN ('해당없음', '정액적립식', '자유적립식')", name=op.f('ck_product_option_reserve_type')),
    sa.CheckConstraint('base_rate >= 0 AND max_rate >= base_rate', name=op.f('ck_product_option_rates')),
    sa.CheckConstraint('period_months > 0', name=op.f('ck_product_option_period_months')),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_product_option_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id', name=op.f('pk_product_option')),
    sa.UniqueConstraint('product_id', 'period_months', 'rate_type', 'reserve_type', name=op.f('uq_product_option_product_id')),
    comment='저축기간별 금리(금감원 optionList 에 대응). 추천·포트폴리오가 실제로 고르는 단위'
    )
    op.create_index('ix_product_option_period_months', 'product_option', ['period_months', sa.literal_column('max_rate DESC')], unique=False)
    op.create_index('ix_product_option_product_id', 'product_option', ['product_id'], unique=False)
    op.create_table('user_holding',
    sa.Column('holding_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.String(length=96), nullable=True, comment='가입한 기간옵션. 상품이 아니라 옵션을 가리켜야 "어느 기간으로 가입했는지"가 남는다'),
    sa.Column('institution', sa.String(length=100), nullable=False, comment='가입 시점 기관명 스냅샷. 원본이 사라져도 보여줘야 한다'),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('monthly_amount', sa.BigInteger(), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='가입 시점 기본금리 스냅샷. 우대 가산 전'),
    sa.Column('effective_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='우대조건까지 반영해 확정된 가입 시점 금리. 적용 내역은 user_holding_condition 에 있다'),
    sa.Column('max_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='가입 시점 상품 최고금리 스냅샷. "광고 7.5% 중 당신은 5.5%" 를 보여주기 위한 값'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'유지중'"), nullable=False),
    sa.CheckConstraint("status IN ('유지중', '만기')", name=op.f('ck_user_holding_status')),
    sa.CheckConstraint('(amount IS NULL OR amount > 0) AND (monthly_amount IS NULL OR monthly_amount > 0)', name=op.f('ck_user_holding_amount_positive')),
    sa.CheckConstraint('amount IS NOT NULL OR monthly_amount IS NOT NULL', name=op.f('ck_user_holding_amount')),
    sa.CheckConstraint('base_rate >= 0 AND base_rate <= effective_rate AND effective_rate <= max_rate', name=op.f('ck_user_holding_rates')),
    sa.CheckConstraint('maturity_date IS NULL OR maturity_date >= start_date', name=op.f('ck_user_holding_maturity_date')),
    sa.ForeignKeyConstraint(['option_id'], ['product_option.option_id'], name=op.f('fk_user_holding_option_id_product_option'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['user_portfolio.portfolio_id'], name=op.f('fk_user_holding_portfolio_id_user_portfolio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_id', name=op.f('pk_user_holding')),
    comment='배분안을 이루는 가입 상품 1건'
    )
    op.create_index('ix_user_holding_maturity_date', 'user_holding', ['maturity_date'], unique=False, postgresql_where=sa.text("status = '유지중'"))
    op.create_index('ix_user_holding_portfolio_id', 'user_holding', ['portfolio_id'], unique=False)
    op.create_table('user_holding_condition',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('holding_id', sa.BigInteger(), nullable=False),
    sa.Column('condition_id', sa.String(length=64), nullable=True, comment='원본 우대조건. 상품이 덮어써지면 NULL 이 되지만 아래 스냅샷은 남는다'),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('rate_bonus', sa.Numeric(precision=4, scale=2), nullable=False, comment='가입 시점에 실제로 가산된 %p. 전부 더하면 effective_rate - base_rate 가 된다'),
    sa.Column('evidence_text', sa.Text(), nullable=True, comment='가산 근거가 된 약관 원문 인용 스냅샷'),
    sa.CheckConstraint('rate_bonus >= 0', name=op.f('ck_user_holding_condition_rate_bonus')),
    sa.ForeignKeyConstraint(['condition_id'], ['product_condition.condition_id'], name=op.f('fk_user_holding_condition_condition_id_product_condition'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['holding_id'], ['user_holding.holding_id'], name=op.f('fk_user_holding_condition_holding_id_user_holding'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_holding_condition')),
    sa.UniqueConstraint('holding_id', 'condition_type', name=op.f('uq_user_holding_condition_holding_id')),
    comment='이 보유 건의 확정금리가 어떻게 나왔는지에 대한 근거. 사용자가 "왜 5.5%?" 라고 물으면 이걸 보여준다'
    )
    op.create_index('ix_user_holding_condition_holding_id', 'user_holding_condition', ['holding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_holding_condition_holding_id', table_name='user_holding_condition')
    op.drop_table('user_holding_condition')
    op.drop_index('ix_user_holding_portfolio_id', table_name='user_holding')
    op.drop_index('ix_user_holding_maturity_date', table_name='user_holding', postgresql_where=sa.text("status = '유지중'"))
    op.drop_table('user_holding')
    op.drop_index('ix_product_option_product_id', table_name='product_option')
    op.drop_index('ix_product_option_period_months', table_name='product_option')
    op.drop_table('product_option')
    op.drop_index('ix_product_condition_product_id', table_name='product_condition')
    op.drop_table('product_condition')
    op.drop_index('ix_special_offer_option_offer_id', table_name='special_offer_option')
    op.drop_table('special_offer_option')
    op.drop_index('ix_product_snapshot_date', table_name='product')
    op.drop_index('ix_product_run_id', table_name='product')
    op.drop_index('ix_product_product_type', table_name='product', postgresql_where=sa.text("parse_status = 'PARSED' AND is_active"))
    op.drop_index('ix_product_institution_code', table_name='product')
    op.drop_table('product')
    op.drop_table('user_profile_tax_exempt')
    op.drop_table('user_profile_social')
    op.drop_index('ix_user_profile_extra_profile_id', table_name='user_profile_extra')
    op.drop_table('user_profile_extra')
    op.drop_table('user_profile_bank')
    op.drop_index('ix_user_portfolio_user_id', table_name='user_portfolio')
    op.drop_index('ix_user_portfolio_profile_id', table_name='user_portfolio')
    op.drop_table('user_portfolio')
    op.drop_index('ix_special_offer_verification_status', table_name='special_offer')
    op.drop_index('ix_special_offer_run_id', table_name='special_offer')
    op.drop_table('special_offer')
    op.drop_index('ix_user_profile_user_id', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_table('social_account')
    op.drop_table('institution_alias')
    op.drop_index('ix_crawl_history_run_id', table_name='crawl_history')
    op.drop_index('ix_crawl_history_page_hash', table_name='crawl_history')
    op.drop_table('crawl_history')
    op.drop_table('institution')
    op.drop_index('ix_batch_run_batch_type', table_name='batch_run')
    op.drop_table('batch_run')
    op.drop_index('ix_app_user_email', table_name='app_user', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('app_user')
    # ### end Alembic commands ###
